[build]
  command = "npm install --legacy-peer-deps && npm run build -- --no-ssr"
  publish = "dist/landing"
  base = "."

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_VERSION = "9.6.7"
  NPM_FLAGS = "--legacy-peer-deps"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 